name: Run Custom Action v0.1.0 branch

on:
  pull_request:
    branches: [main]

jobs:
  run-action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run custom action
        id: run-action
        uses: ./
        with:
          github_branch: feature/branch

      - name: Test Success
        if: ${{ steps.run-action.outputs.tags != 'branch' }}
        run: |
          echo "tags: ${{ steps.run-action.outputs.tags }}"
          exit 1
